name: Runner

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    services:
      flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
          - 8191:8191
        env:
          LOG_LEVEL: debug
          CAPTCHA_SOLVER: none
        options: --health-cmd "curl -s http://localhost:8191 || exit 1" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests

    - name: Wait for FlareSolverr to be ready
      run: |
        timeout 60s bash -c "until curl -s http://localhost:8191 > /dev/null; do echo 'Waiting for FlareSolverr...'; sleep 2; done" || {
          echo "FlareSolverr failed to start. Checking container logs..."
          docker logs $(docker ps -q -f name=flaresolverr)
          exit 1
        }
        echo "FlareSolverr is up!"

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Run
      run: python runner.py
