name: Runner

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    services:
      flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
          - 8191:8191
        env:
          LOG_LEVEL: debug  # Increased logging for diagnostics
          CAPTCHA_SOLVER: none

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests

    - name: Wait for FlareSolverr to be ready
      run: |
        timeout 30s bash -c "until curl -s http://flaresolverr:8191 > /dev/null; do echo 'Waiting for FlareSolverr...'; sleep 2; done"
        echo "FlareSolverr is up!"

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run
      run: python runner.py
